broker:
  test: default

spring:
  redis:
    host: localhost
    port: 6379


  jpa:
    hibernate:
      ddl-auto: none
      generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        format_sql: true
        use_sql_comments: true

  datasource:
    url: jdbc:mysql://localhost:3306/study
    username: root
    password: password
